pipeline {
    agent {
        docker {
            image '127.0.0.1:30400/puzzle:latest'
            args '-v $HOME/.m2:/root/.m2'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'docker build -t 127.0.0.1:30400/puzzle:latest -f /home/rthuerta/kubernetes-ci-cd/applications/puzzle/Dockerfile /home/rthuerta/kubernetes-ci-cd/applications/puzzle/'
            }
        }
    }
}
